name: Docker Image CI

on:
  push:
    branches: [ 20.06.15-cdk1.55.0 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ubuntu/standard/4.0 && docker build . --squash --file Dockerfile --tag seedrun/codebuild-standard:4.0-20.06.15-cdk1.55.0
